### ISSUE TITLE
Uncaught ReflectionException: Class translator does not exist

### ISSUE THREAD

**Issue by tyler36** [olssonm/l5-very-basic-auth#11]
Hi and thanks for creating the package.

I have a multi-lingual site and would like to customize the 'opt out / cancel' message.
I tried updated the 'very_basic_auth.php' config file to include
```
'error_message'     =>  trans('auth.opt_out')
```

but get an error. Is this supported? Is there a different way of doing this? 

Thanks in advance

**Comment by olssonm** [comment]
Hello – yeah, this is because when laravel reads the config-file helpers like `trans()`, `view()`, `session()` etc. hasn't been loaded yet.

But I do see your issue – having a translatable string available to the users are perhaps useful. I'll see what I can come up with.

**Comment by olssonm** [comment]
A new version is up (2.1.0) which adds the ability to set a view for the response to the user.

In this view you can use the `trans()`-method among other things.

Please try it out and file a ticket if you run into any issues.

**Comment by tyler36** [comment]
Confirmed working. 
Thank you for taking the time. I'm sure others will benefit from this too!

**Comment by olssonm** [comment]
Great – you're welcome =)
