### ISSUE TITLE
従業員求む。

### ISSUE THREAD

**Issue by olssonm** [olssonm/l5-very-basic-auth#16]
このパッケージは日本人のユーザーがたくさんいるますけど、ドキュメンテーションは英語だけです。誰かが私を助けることができますか。

(すみません、私の日本語はあまりよくないんです)

**Comment by kazuhei** [comment]
Hello! I'm Japanese developer. And I want translation this package documentation because It's very useful package.

**Comment by olssonm** [comment]
Hey! Thanks! You're more than welcome to help out when/if you find the time =)

I prepared a branch here: https://github.com/olssonm/l5-very-basic-auth/tree/i18n-japanese with the file "[README.jp.md](https://github.com/olssonm/l5-very-basic-auth/blob/i18n-japanese/README.jp.md)". We don't need a 100% translation, just the **Installation**, **Configuration** and **Usage** really, whatever that might help people out. 

Feel free to do some translation whenever you have the time and then submit a PR. Thanks!

**Comment by kazuhei** [comment]
OK! Leave it to me!

**Comment by olssonm** [comment]
Again, a big thank you @kazuhei for your help! =)
