### ISSUE TITLE
PHP 7 support / issue

### ISSUE THREAD

**Issue by zeecodes** [olssonm/l5-very-basic-auth#24]
Switched my environment from PHP 5.6 to 7.2 and prompt still works however after entering the correct password, it declines it.

As soon as I switch over to 5.6, the username/password combination works again.

I know PHP 7 is not supported but it would really help to support it in my situations where people are upgrading or migrating their hosts.

**Comment by olssonm** [comment]
That sounds odd; PHP 7 (and also 7.1, 7.2) is very much supported, and has been for quite some time (the last builds tests: https://travis-ci.org/olssonm/l5-very-basic-auth). I'm not sure that the PHP-version is the cause for your issues per see.

What version of l5-very-basic-auth are you using? And what version of Laravel? 

When switching environments; are you sure that you update and reinstall the packages via `composer install` to check for the correct dependencies?

It could also be an issue with your environments; have you checked that Laravel detects the correct environment when switching PHP-versions – and that you have set the corresponding environments in `config/very_basic_auth.php`?

**Comment by zeecodes** [comment]
l5-very-basic-auth version 1.2
Laravel version 5.2
PHP version 7.1

I just read your note on readme.md, I assume only l5-very-basic-auth 5.* supports PHP 7?

Thanks for the prompt reply!

**Comment by olssonm** [comment]
Hmm, if you remove ` Olssonm\VeryBasicAuth\VeryBasicAuthServiceProvider::class` from your app.pgp and then run `composer remove l5-very-basic-auth`; and then again try with `composer require l5-very-basic-auth` – what version of l5-very-basic-auth do you get then?

There might be an issue where the Laravel 5.2 and PHP 7.x-combo isn't available for the package. If so, I can go back and add a bump on the 1.2-branch.

**Comment by zeecodes** [comment]
Hi olssonm,

That is the output I get:

root@e6f5636a9148:/var/www/laravel# composer require olssonm/l5-very-basic-auth
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Using version ^5.1 for olssonm/l5-very-basic-auth
./composer.json has been updated
> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for olssonm/l5-very-basic-auth ^5.1 -> satisfiable by olssonm/l5-very-basic-auth[v5.1].
    - Conclusion: remove laravel/framework v5.2.45
    - Conclusion: don't install laravel/framework v5.2.45
    - olssonm/l5-very-basic-auth v5.1 requires illuminate/support ~5.4.0|~5.5.0|~5.6.0 -> satisfiable by illuminate/support[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.2, v5.6.3, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - don't install illuminate/support v5.4.0|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.4.13|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.4.17|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.4.19|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.4.27|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.4.36|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.4.9|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.5.0|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.5.16|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.5.17|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.5.2|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.5.28|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.5.33|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.5.34|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.5.35|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.5.36|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.5.37|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.5.39|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.6.0|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.6.1|don't install laravel/framework v5.2.45
    - illuminate/support v5.6.10 conflicts with laravel/framework[v5.2.45].
    - illuminate/support v5.6.11 conflicts with laravel/framework[v5.2.45].
    - illuminate/support v5.6.12 conflicts with laravel/framework[v5.2.45].
    - illuminate/support v5.6.13 conflicts with laravel/framework[v5.2.45].
    - illuminate/support v5.6.14 conflicts with laravel/framework[v5.2.45].
    - don't install illuminate/support v5.6.2|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.6.3|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.6.4|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.6.5|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.6.6|don't install laravel/framework v5.2.45
    - don't install illuminate/support v5.6.7|don't install laravel/framework v5.2.45
    - illuminate/support v5.6.8 conflicts with laravel/framework[v5.2.45].
    - illuminate/support v5.6.9 conflicts with laravel/framework[v5.2.45].
    - Installation request for laravel/framework (locked at v5.2.45, required as 5.2.*) -> satisfiable by laravel/framework[v5.2.45].


Installation failed, reverting ./composer.json to its original content.

**Comment by olssonm** [comment]
Thanks! Yepp, seemed to be an issue with Laravel 5.2 coupled with Laravel 7.x.

I've published a new release; 1.2.2 that should sort this out. Simply use `composer require olssonm/l5-very-basic-auth "~1.2"`. This release is usable with Laravel 5.1/Laravel 5.2 together with either PHP 5.6 or 7.x.

Hope it works out for you, else feel free to get back to me and I'll look for another solution =)

**Comment by zeecodes** [comment]
You dear sir, are awesome! Thanks so much, that fixed the issue.
