### ISSUE TITLE
Request - Config & Inline Credentials

### ISSUE THREAD

**Issue by kevyworks** [olssonm/l5-very-basic-auth#25]
Hi, as the title suggests;

```php
# Inline
Route::group(['middleware' => 'auth.very_basic:admin,password'], function() {
    ...
});

# Config
Route::group(['middleware' => 'auth.very_basic:services.xservice.basic_auth'], function() {
    ...
});

```

Basically the `config` part can be negated as can be used as:

```php
Route::group([ 'middleware' => 'auth.very_basic:' . config('services.xservice.basic_auth') ], function() {
    ...
});
```

**Comment by olssonm** [comment]
Hey, thanks for your feedback.

That's not a bad idea, I will look into it. However, that syntax doesn't fit if you want to use custom views or messages for example (becomes many and long parameters), but for username and password it should be doable.

**Comment by kevmt** [comment]
@olssonm Hi, this is what I have currently: https://gist.github.com/kevmt/e69e61d5ec55fad49e8b92900d9f38f5

**Comment by olssonm** [comment]
Excellent – will look into combining the two.

**Comment by luria** [comment]
Hi there. Any update on this?
Looks like a very useful feature (user,password) to separate areas for different users.
Is there another way to implement something similar?
Thanks for your time!

**Comment by olssonm** [comment]
@luria – Yes, it's been taking a while =/ Will look into it and merge, will be back in a day or two.

**Comment by olssonm** [comment]
@luria A new release is out, v5.6: https://github.com/olssonm/l5-very-basic-auth/releases/tag/v5.6 that allows for inline credentials directly in your routes.

Thanks also to @kevyworks for suggesting this!

**Comment by luria** [comment]
@olssonm Thank you so much for the update. It works really well.
Also thanks to @kevyworks for the suggestion and the code.
You guys rock!
