### ISSUE TITLE
Disable prompting for authentication details

### ISSUE THREAD

**Issue by judgej** [olssonm/l5-very-basic-auth#29]
Thank you. Package works great - straight out of the box, though the creation of the config file in the vendor folder (which should be write-only to web processes) is a little disconcerting.

Anyway, my requirement. I would like to be able to protect a route or group using basic auth details, but I don't want the browser to pop up with a user credentials box. This is specifically for a machine-to-machine API, so no user will ever be logging in, and any user encountering the route should not be given clues that basic auth is in place on that route.

The idea is just to return a `401` without the `WWW-Authenticate` header, or better still a `404` - no clues that a route is there.

Obviously it's not going to stop a brute force attempt given the knowledge about the route, but a little security-by-obscurity should help to reduce the likelihood of it happening.

Is this something you would be interested in supporting, if I had a PR?

**Comment by judgej** [comment]
I guess this would be like a "hidden page" - you come to it with the correct authentication header, or you just don't see that it is there at all.

**Comment by olssonm** [comment]
Thanks for your input! I think I understand what you are looking for.

You always have the option to pass the username/password in the URL (i.e. http://username:password@example.com) to access a resource without a prompt. To protect an API I do think however that you should use OAuth or a custom middleware where you validate an access-token or the like.

Also, the config-file is placed inside the default config-folder, and you should use your .env-file to store your password to not commit it to Git or the like.

The purpose of this package is to enable a simple login using HTTP basic auth without a database, so your requirements are most likely outside the scope of this project. 

[RFC 2617](https://tools.ietf.org/html/rfc2617) for HTTP Authentication also states:

```
The 401 (Unauthorized) response message is used by an origin server
to challenge the authorization of a user agent. This response MUST
include a WWW-Authenticate header field containing at least one
challenge applicable to the requested resource.
```

So I do not feel too comfortable in trying to build methods to circumvent this. 

I hope I understood your request correctly?

**Comment by judgej** [comment]
Yes I agree there are better ways to protect the API. In this case a supplier service is sending us callback/notification messages, and they say this is what we must do. There are further layers of security here anyway.

I tried that URL username password in Firefox, and it just remove it. I think most browsers have been disabling that option for a while now.

I can achieve what I need just by commenting out the "with header" lines. What I will probably do then, is fork this package to create a new authorization type. The two differences will be:

* The `WWW-Authenticate` header is not returned. The consumer either has valid details or does not, but are never challenged for them if not valid or not supplied.
* If validation fails, a `404` is returned, so the URI just does not show up as being there. If we don't return a `401`, then we don't have to return the `WWW-Authenticate` header, so will remain compliant. sort of ;-)

**Comment by olssonm** [comment]
Yeah, sorry – I will not be adding this feature.

If I were you I would just create a new middleware:

```shell
php artisan make:middleware AccessMiddleware
```

Add it to a new middleware-group in Kernel.php and then check for user and password:

```php
public function handle($request, Closure $next)
{
    if ($request->getUser() != env('MY_USER') || $request->getPassword() != env('MY_PASS)) {
        return $next($request);
    }

    return app()->abort(404);
}
```

Very simple and no need for any packages or extra "fluff".
