### ISSUE TITLE
Stuck in authentication loop

### ISSUE THREAD

**Issue by repat** [olssonm/l5-very-basic-auth#5]
Hi,

every time I open the my test page I get the prompt to enter details, enter them and get another prompt. This is due to the fact, that `$request->getUser()` and `$request->getPassword()` are always empty. In postman and curl I simply get the error message.

I installed laravel in a subfolder, could it be some redirect issue? Maybe I have to enter something in .htaccess?

thanks

**Comment by olssonm** [comment]
Hi, sorry for late reply (been afk for a while).

Anyhow, using subdirectory shouldn't matter – I'm more leaning into that it's an Apache/Server-issue.

Let's do some testing; 

1. Have you set an `APP_KEY` in your Laravel-environment?
2. If you do a `dd(app('request')->server);`, do you get the `PHP_AUTH_USER`, `PHP_AUTH_PW` and/or `HTTP_AUTHORIZATION`?

Basic auth should work out of the box with NGINX, haven't worked much with it with Apache. As you say, it may very well be related to your .htaccess. If you don't get the parameters in "2" above, try checking out this thread that seems related: http://laravel.io/forum/05-10-2014-http-basic-auth-always-fails-on-ipage

**Comment by repat** [comment]
No worries :) Thanks for supporting even if it's not the packages fault.

1. yes
2. I don't know where exactly I would put that. If I put it in the test method in the controller, it's never reached because I just get the authentication prompt over and over again. If I put it in the middleware, it's executed before the authentication header is sent, which triggers the authentication in the first place. When I cancel the auth request I get the output, but none of the above variables, even when I send the auth details with postman. Maybe I misunderstood? I'm new to Laravel.

I'm on a plane at the moment (free WiFi at Norwegian Air :)) so it's kind of a pain to test with satellite Internet but I'll try the tip from the laravel.io forum and get back to you. Seems like a pretty big hack though. I also did some further digging and found out it might be due to the fact that I run PHP 5.6 via fastcgi. Since it's on a managed server, I don't have much influence on these things.

I guess worst case is that I just have configure all of the authentication in a .htaccess with .htpasswd -.-

**Comment by olssonm** [comment]
Regarding `dd(app('request')->server);`: try authenticating once, then remove the `auth.very_basic`-filter on any route, and just put `dd(app('request')->server);`. If everything is configured as it is supposed to – a whole array of values should be outputed, among them `PHP_AUTH_USER`, `PHP_AUTH_PW` and `HTTP_AUTHORIZATION`.

Also, just to make sure, surely you've run `$ php artisan vendor:publish`? =)

**Comment by repat** [comment]
Yes, I do get an array, with 

> "REDIRECT_REDIRECT_REMOTE_USER" => "Basic dXNlcjpwYXNzd29yZA=="

I've never seen it before like this. I'm googeling it now..

`dXNlcjpwYXNzd29yZA==` translates to `user:password` (which is what I set in the config file).

As far as I understood `php artisan vendor:publish` is to copy the config files from the vendor/ folder to config/? I think I did that, anyway I just did it again, before writing this. And the file definitely existed. Even so, I logged `$request->getUser()` and `$request->getPassword()`, and they shouldn't be empty.

**Comment by repat** [comment]
So you can do this:

```php
list($user, $password) = explode(':', base64_decode(substr($_SERVER["REDIRECT_REDIRECT_HTTP_AUTHORIZATION"], 6)));
```

if you have this in your .htaccess:

> RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

(notice it said `REMOTE_USER` before, I changed it to `HTTP_AUTHORIZATION`, also since it's not the last Rewrite Rule, you can't use `L` here like in the quote from above).

Anyway, the extration of the username and password works like that, although it feels quite hacky. But then the Closure `$next` is called and that doesn't work again, because it seems to be empty. So just like all the other things in the request, the `REQUEST_URI` is not included (although visible in `dd(app('request')->server);` if you remove the middleware after authenticating once) and therefore the user can't be redirected to the `REQUEST_URI` that is protected by the middleware. Seems like we  would have to solve this at the very core. Although the `REMOTE` and `REMOTE_REMOTE` prefix are not in front of `REQUEST_URI`... But calling the Closure on the `$request` object fails anyway. I don't really know Symfony well enough either :-/

Printing the `$request` variable ends in recursion and crashes the browser ;)

I also use `Route::group(['prefix' => 'myPrefix'])` btw.

**Comment by olssonm** [comment]
Cool! I'm looking into building a solution directly into the package. Might I ask what hosting solution you are using?

**Comment by repat** [comment]
It's a managed server at https://all-inkl.com/server/server_l/ (would not have been my first choice but I didn't have a say in this ;))

**Comment by olssonm** [comment]
Great, I'll look into it. Opened a new issue here; #6 – would be cool if there is a fix directly in the package for the folks that are stuck in a shared non-configurable environment. 

Might get back to you when an update is ready and some testing is needed =)

**Comment by repat** [comment]
Cool, thanks a lot. I think basically you would have to use that .htacces line and then go through the request and see at which point (how many `REDIRECT_` there are) you find "Basic XXXX".

For now, I also put this in the config file, as well as an entry for `mb_strlen("Basic ")` (including space), so it's clear why the substr() begins at 6.
