### ISSUE TITLE
Support for encrypted password

### ISSUE THREAD

**Issue by ejerskov** [olssonm/l5-very-basic-auth#53]
Would be nice if you could input an encrypted password in the config file so that its not in clear text.

**Comment by olssonm** [comment]
@ejerskov You should not keep your password in the config-file, instead you should store it in your .env or as an environment-variable, just as you would with API-keys and the like.

very_basic_auth.php:
```
return [
    'password' => env('PASSWORD')
];
```

.env:
```
PASSWORD=my_password
```

That way I see no need to use encryption or decryption.

**Comment by ejerskov** [comment]
Thanks!
