### ISSUE TITLE
Laravel Debugbar is injecting itself even on Unauthorized access responses

### ISSUE THREAD

**Issue by antonioribeiro** [olssonm/l5-very-basic-auth#58]
This is a huge security risk for debug/test environments.

Seems like you should not respond with a Laravel response object.

<img width="1529" alt="Screen Shot 2022-04-22 at 12 02 24" src="https://user-images.githubusercontent.com/3182864/164684786-efc1b6df-4f65-4a87-aead-d9e7c19f016e.png">

**Comment by olssonm** [comment]
@antonioribeiro Thanks for your feedback!

Hmm, I don't think I see the security implications; if your have your application set to `debug=true` and/or debugbar enabled, shouldn't you expect the response to contain debug-information? Currently I see this as an intended feature.

Natively Laravel Debugbar is included in 403-responses and the like. This is why you are warned when using debug in a production environments etc. 

If you want to, please provide more info on why this should be considered a security issue and I'll happily look into it!

**Comment by antonioribeiro** [comment]
We have Staging applications (for end-user testing) that we keep the `debug=true` to understand application behaviour when users report bugs. We need debug=true, but also prevent debugbar from leaking it to non-authorized users.

Adding it at the webserver level fixes this, but the idea is to have the application controlling basic auth access, so we don't need to reconfigure auth basic for every new subdomain we point to the same application (on Forge, for example).

**Comment by olssonm** [comment]
Gotcha, thanks for the explainer. 

I see the current workings as the default, my guess is that most people expect the debug-info to be displayed when debug is set to `true`.

However, I also understand your specific use-case. There might be a point to add the ability to use a custom-response object to the configuration, so if for any reason (for example to not include the debugbar in the response) the user may do so, i.e.:

``` php
// very_basic_auth.php
// default
'response_handler' => \Olssonm\VeryBasicAuth\Response::class

// custom
'response_handler' => \App\Http\CustomResponse::class
```

Then in the custom response you could just have (very simplified example)
``` php
class CustomResponse implements \Olssonm\VeryBasicAuth\Response {
  function handle() {
    return 'My message';
  }
}
```

Can't promise a quick edit, but I'll look into and see if something like this – or similar – is worth adding.

**Comment by antonioribeiro** [comment]
Great, thank you!

**Comment by olssonm** [comment]
v6.8 now offers the ability to set a customizable response handler, in which you theoretically can write your own handler that excludes php debug output (and other things too), via for example going for the config route with `config()->set('debugbar.enabled', false)` before returning the  response. 

Still recommended to not use debug on a publicly available production/staging instance however =)
