### ISSUE TITLE
Error - Failed to open stream: Permission denied

### ISSUE THREAD

**Issue by bianchi** [olssonm/l5-very-basic-auth#62]
I'm having this error in my production logs:

`file_put_contents(/var/www/vendor/olssonm/l5-very-basic-auth/src/config.php): Failed to open stream: Permission denied`

It happens every few seconds. Besides that the authentication is working.

I have published the configuration file in my config folder.

**Comment by olssonm** [comment]
@bianchi Thanks for reaching out. Yeah, you seem to have a clash there where the system tries to write to `/var/www/vendor/olssonm/l5-very-basic-auth/src/config.php`, and the system isn't the same owner as the one that installed the package via composer.

However, this shouldn't happen if you have published the config-file. Can you just double-confirm that in your project that you have a file named `/config/very_basic_auth.php`? And I'll work on a solution.

Thanks!

**Comment by olssonm** [comment]
@bianchi This should now be solved with the [v7.0-release](https://github.com/olssonm/l5-very-basic-auth/releases/tag/v7.0). Please update and get back to me if you encounter any other issues.

**Comment by bianchi** [comment]
I'll do that. Thank you @olssonm
