### ISSUE TITLE
[Info] Can't load page using very-basic-auth at all on emphaty browser on raspberry pi one Model B

### ISSUE THREAD

**Issue by okaufmann** [olssonm/l5-very-basic-auth#8]
Hi,

I'm using your package for a fork of a dashboard package.
I'd like to show the page on a old raspberry pi in the Epiphany Browser (v3.8.2) in kiosk mode.

But the site could not been loaded. The browser don't stop loading the page and don't show the authentication dioalog as expected.

Since I can solve this with native apache basic authentication, this is not critical at all. But I thought this could be a Problem with some Browsers want to be fixed.

Hope it helps.

**Comment by olssonm** [comment]
Hi, thanks for the feedback and reporting!

You wouldn't happen to be running an Apache/CGI-combo on your server? Have you tested other browsers, or is this issue very much exclusive to the Epiphany Browser?

The Apache/CGI-combo do have some known issues with basic authentication, take a look at this if it helps: https://github.com/olssonm/l5-very-basic-auth/issues/6 (earlier reported here: https://github.com/olssonm/l5-very-basic-auth/issues/5).

I've tried to fix this similar issue before, just having a tough time getting a hold of a good testing environment and tools for this =/

**Comment by okaufmann** [comment]
Hi,

I'm not sure. This Project runs on my shared hosting instance. They use LiteSpeed V6.9 (https://www.litespeedtech.com/products/litespeed-web-server/overview), which is a apache compatible webserver. Possible its a combo with CGI.

The only evidence I have ist this section in phpinfo():
![image](https://cloud.githubusercontent.com/assets/4414498/16644746/74466724-441f-11e6-900d-f9a65d61e7a1.png)

Just met this Problem with the Epiphany Browser.

I'll test the workaround described in https://github.com/olssonm/l5-very-basic-auth/issues/6 asap.

If you expirienced in Docker you could easy setup several containers with different Webservers to test your package?
